language: php

sudo: false

dist: focal

env:
  - COMPOSER_OPTS="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
      - php: 7.4

before_install:
    # disable xdebug if available
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    # disable default memory limit
    - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI
    # enable apcu
    - echo "extension=apcu.so" >> $INI
    - yes '' | pecl install imagick gd

install:
  - travis_retry composer install $COMPOSER_OPTS

script:
  - vendor/bin/phplint ./src
  - vendor/bin/phpcs -d memory_limit=-1 --standard=PSR2 --extensions=php ./src
  - vendor/bin/phpspec run
